// src/components/pages/checkout/delivery-select/index.tsx
import { Forward } from "@/components/icons";
import { DELIVERY_TYPES } from "@/lib/constants";
import { useAppDispatch, useAppSelector } from "@/lib/hooks";
import { updateDeliveryType } from "@/lib/store/orderSlice";
import classNames from "classnames";
import { Fragment, useCallback, useState } from "react";

export default function DeliverySelect() {
  const [isOpen, setOpen] = useState(false);
  const dispatch = useAppDispatch();
  const { delivery } = useAppSelector((state) => state.order);

  const getItem = useCallback((del: typeof delivery, callback: () => void) => {
    return (
      <div
        className="flex items-center justify-between flex-grow"
        onClick={callback}
      >
        <span>{del.title}</span>
        <span>{del.price == "FREE" ? del.price : `$${del.price}`}</span>
      </div>
    );
  }, []);
  return (
    <div className="my-8">
      <span className="uppercase text-base text-gray-placeholder mb-3 flex">
        Shipping Method
      </span>
      <div className="relative">
        <div className="flex items-center justify-between py-[13px] px-5 bg-[#F9F9F9] rounded-[44px] cursor-pointer">
          {getItem(delivery, () => setOpen(!isOpen))}
          <Forward />
        </div>
        <div
          className={classNames(
            "bg-[#F9F9F9] px-4 py-2 rounded-2 absolute top-full left-0 w-full mt-2 gap-2 transition-all flex flex-col",
            isOpen ? "opacity-1 visible" : "opacity-0 invisible"
          )}
        >
          {DELIVERY_TYPES?.map((c) => (
            <Fragment key={c.title}>
              {getItem(c, () => {
                dispatch(updateDeliveryType(c));
                setOpen(false);
              })}
            </Fragment>
          ))}
        </div>
      </div>
    </div>
  );
}

// nuxt-version/components/pages/checkout/delivery-select.vue
<script setup lang="ts">
import ForwardIcon from "@/components/icons/forward-icon.vue";
import { DELIVERY_TYPES } from "@/shared/constants";
import { cn } from "@/shared/utils";
import { useOrderStore } from "@/shared/stores";
import { storeToRefs } from "pinia";
import { ref } from "vue";

const isOpen = ref(false);

const orderStore = useOrderStore();
const { delivery } = storeToRefs(orderStore);

const onOpen = (v: boolean) => (isOpen.value = v);

const onUpdate = (c: { title: string; price: string | number }) => {
  orderStore.updateDeliveryType(c);
  onOpen(false);
};
</script>
<template>
  <div class="my-8">
    <span class="uppercase text-base text-gray-placeholder mb-3 flex">
      Shipping Method
    </span>
    <div class="relative">
      <div
        class="flex items-center justify-between py-[13px] px-5 bg-[#F9F9F9] rounded-[44px] cursor-pointer"
      >
        <div
          class="flex items-center justify-between flex-grow"
          @click="() => onOpen(!isOpen)"
        >
          <span>{{ delivery.title }}</span>
          <span>{{
            delivery.price == "FREE" ? delivery.price : `$${delivery.price}`
          }}</span>
        </div>
        <ForwardIcon />
      </div>
      <div
        :class="
          cn(
            'bg-[#F9F9F9] px-4 py-2 rounded-2 absolute top-full left-0 w-full mt-2 gap-2 transition-all flex flex-col',
            isOpen ? 'opacity-100 visible' : 'opacity-0 invisible'
          )
        "
      >
        <div
          v-for="c in DELIVERY_TYPES"
          :key="c.title"
          class="flex items-center justify-between flex-grow"
          @click="() => onUpdate(c)"
        >
          <span>{{ c.title }}</span>
          <span>{{ c.price == "FREE" ? c.price : `$${c.price}` }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
