// nuxt-version/components/pages/checkout/add-card.vue
<script setup lang="ts">
import InputUi from "@/components/ui/input-ui.vue";
import type { CardType } from "@/shared/type";
import { cn } from "@/shared/utils";
import { useOrderStore } from "@/shared/stores";
import { storeToRefs } from "pinia";
import { onMounted, reactive, ref } from "vue";
import AddCardView from "./add-card-view.vue";
import BottomBar from "./bottom-bar.vue";
import TabContainer from "./tab-container.vue";

const orderStore = useOrderStore();

const { card } = storeToRefs(orderStore);

const rotateCard = ref(false);

const cardDetails = reactive({
  cardOwner: "",
  cardNumber: "",
  expiredDate: "",
  CVV: "",
});

onMounted(() => {
  if (card) {
    Object.entries(card.value as CardType).forEach(([key, value]) => {
      cardDetails[key as keyof typeof cardDetails] = value;
    });
  }
});

const handleChange =
  (key: keyof typeof cardDetails, rotate?: boolean) => (value: string) => {
    cardDetails[key] = value;
    rotateCard.value = rotate || false;
  };

const isValid = () => Object.values(cardDetails).every(Boolean);

const onAddCard = () => {
  orderStore.updateCardDetails(cardDetails);
  orderStore.changeTab(1);
};

const inputStyle =
  "pb-4 border-b border-[#D4D4D4] focus:outline-none hover:outline-none autofill:bg-none";
</script>

<template>
  <TabContainer
    :tabNumber="3"
    topTitle="Payment method"
  >
    <AddCardView
      :rotateCard="rotateCard"
      :cardDetails="cardDetails"
    />
    <div
      class="mt-8 max-w-[900px] w-full mx-auto gap-6 flex flex-grow flex-col"
    >
      <InputUi
        :class="cn(inputStyle)"
        placeholder="Name on Card"
        inputType="text"
        :value="cardDetails?.cardOwner"
        :onChange="handleChange('cardOwner')"
      />
      <InputUi
        :class="cn(inputStyle)"
        placeholder="Card Number"
        inputType="card_number"
        :value="cardDetails?.cardNumber"
        :onChange="handleChange('cardNumber')"
      />
      <InputUi
        :class="cn(inputStyle)"
        placeholder="Exp date"
        inputType="exp_date"
        :value="cardDetails?.expiredDate"
        :onChange="handleChange('expiredDate')"
      />

      <InputUi
        placeholder="CVV"
        inputType="ccv"
        :class="cn(inputStyle)"
        :value="cardDetails?.CVV"
        :onChange="handleChange('CVV', true)"
      />
    </div>
    <BottomBar
      :buttonText="`${!card ? 'Add' : 'Update'} Card`"
      :onClick="onAddCard"
      :disabled="!isValid()"
    />
  </TabContainer>
</template>

// src/components/pages/checkout/add-card/index.tsx
import AddCardView from "@/components/pages/checkout/add-card/add-card-view";
import Input from "@/components/ui/input";
import { useAppDispatch, useAppSelector } from "@/lib/hooks";
import { changeTab, updateCardDetails } from "@/lib/store/orderSlice";
import classNames from "classnames";
import { useCallback, useMemo, useState } from "react";
import BottomPart from "../bottom-bar";
import TabContainer from "../tab-container";

export default function AddCard() {
  const dispatch = useAppDispatch();
  const { card } = useAppSelector((state) => state.order);

  const [rotateCard, setRotate] = useState(false);

  const [cardDetails, setDetails] = useState({
    cardOwner: card?.cardOwner || "",
    cardNumber: card?.cardNumber || "",
    expiredDate: card?.expiredDate || "",
    CVV: card?.CVV || "",
  });

  const onChange = useCallback(
    (key: keyof typeof cardDetails, value: string, rotate: boolean) => {
      setDetails((prev) => ({ ...prev, [key]: value }));
      setRotate(rotate);
    },
    []
  );

  const isValid = useMemo(
    () => Object.values(cardDetails).every(Boolean),
    [cardDetails]
  );

  const onAddCard = useCallback(() => {
    if (isValid) {
      dispatch(updateCardDetails(cardDetails));
      dispatch(changeTab(1));
    }
  }, [cardDetails, isValid]);

  const inputStyle =
    "pb-4 border-b border-[#D4D4D4] focus:outline-none hover:outline-none autofill:bg-none";

  return (
    <TabContainer
      tabNumber={3}
      topTitle="Payment method"
    >
      <AddCardView
        rotateCard={rotateCard}
        cardDetails={cardDetails}
      />
      <div className="mt-8 max-w-[900px] w-full mx-auto gap-6 flex flex-grow flex-col">
        <Input
          className={classNames(inputStyle)}
          placeholder="Name on Card"
          inputType="text"
          value={cardDetails?.cardOwner}
          onChange={(value) => onChange("cardOwner", value, false)}
        />
        <Input
          className={classNames(inputStyle)}
          placeholder="Card Number"
          inputType="card_number"
          value={cardDetails?.cardNumber}
          onChange={(value) => onChange("cardNumber", value, false)}
        />
        <Input
          className={classNames(inputStyle)}
          placeholder="Exp date"
          inputType="exp_date"
          value={cardDetails?.expiredDate}
          onChange={(value) => onChange("expiredDate", value, false)}
        />

        <Input
          placeholder="CVV"
          inputType="ccv"
          className={classNames(inputStyle)}
          value={cardDetails?.CVV}
          onChange={(value) => onChange("CVV", value, true)}
        />
      </div>
      <BottomPart
        buttonText={`${!card ? "Add" : "Update"} Card`}
        onClick={onAddCard}
        disabled={!isValid}
      />
    </TabContainer>
  );
}
