// next-version/src/components/common/dialogs/menu-dialog/index.tsx
import Divider from "@/components/common/divider";
import Socials from "@/components/common/socials";
import { Location, Phone } from "@/components/icons";
import Modal from "@/components/ui/modal";
import ModalClose from "@/components/ui/modal/modal-close";
import { MENU_TABS } from "@/lib/constants";
import { DialogPropType } from "@/lib/type";
import Link from "next/link";
import { useState } from "react";
import NavItem from "./menu-item";
import NavTabs from "./menu-tabs";

export default function Nav({ open, onOpenChange }: DialogPropType) {
  const [tab, setTab] = useState(0);

  return (
    <Modal isOpen={open}>
      <ModalClose action={onOpenChange} />
      <NavTabs
        tabChange={setTab}
        tabs={MENU_TABS}
      />
      <div className="flex flex-col mt-6">
        {MENU_TABS[tab].list?.map((c) => (
          <NavItem
            {...c}
            key={c.title}
          />
        ))}
      </div>
      <div className="flex flex-col gap-4 my-6">
        <Link
          href="tel:(786) 713-8616"
          className="flex items-center gap-4 text-base font-sans"
        >
          <Phone /> (786) 713-8616
        </Link>
        <Link
          href="https://example.com/"
          target="_blank"
          className="flex items-center gap-4 text-base font-sans"
        >
          <Location /> Store locator
        </Link>
      </div>
      <Divider className="mx-auto w-32 mb-12" />
      <Socials />
    </Modal>
  );
}

// vue-version/src/components/common/dialogs/menu-dialog/menu-dialog.vue
<script setup lang="ts">
import Divider from '@/components/common/divider-comp.vue'
import Socials from '@/components/common/socials-comp.vue'
import Location from '@/components/icons/location-icon.vue'
import Phone from '@/components/icons/phone-icon.vue'

import CommonLink from '@/components/common/common-link.vue'
import ModalClose from '@/components/ui/modal-ui/modal-close.vue'
import Modal from '@/components/ui/modal-ui/modal-ui.vue'
import { MENU_TABS } from '@/lib/constants'
import type { DialogPropType } from '@/lib/type'
import { computed, ref } from 'vue'
import NavItem from './menu-item.vue'
import NavTabs from './menu-tabs.vue'

const { open, onOpenChange } = defineProps<DialogPropType>()

const tab = ref(0)
const onTabChange = (value: number) => (tab.value = value)

const items = computed(() => MENU_TABS[tab.value].list)
</script>

<template>
  <Modal :isOpen="open">
    <ModalClose :action="onOpenChange" />
    <NavTabs :tabChange="onTabChange" :tabs="MENU_TABS" />
    <div class="flex flex-col mt-6">
      <NavItem :item="c" v-for="c in items" :key="c.title" />
    </div>
    <div class="flex flex-col gap-4 my-6">
      <CommonLink
        external
        to="tel:(786) 713-8616"
        class="flex items-center gap-4 text-base font-sans"
      >
        <Phone /> (786) 713-8616
      </CommonLink>
      <CommonLink
        external
        to="https://example.com/"
        target="_blank"
        class="flex items-center gap-4 text-base font-sans"
      >
        <Location /> Store locator
      </CommonLink>
    </div>
    <Divider class="mx-auto w-32 mb-12" />
    <Socials />
  </Modal>
</template>
