// vue-version/src/components/pages/checkout/saved-block/address-item.vue
<script setup lang="ts">
import type { AddressType } from '@/lib/type'

const { address } = defineProps<{ address: AddressType }>()
</script>

<template>
  <div className="flex flex-col grow">
    <span className="text-lg text-[#1A1A1A] mb-2"> {{ address.fname }} {{ address.lname }} </span>
    <span className="text-base text-[#555555]">{{ address.address }}</span>
    <span className="text-base text-[#555555]">
      {{ address.city }},{{ address.state }},{{ address.zipCode }}
    </span>
    <span className="text-base text-[#555555]">{{ address.phone }}</span>
  </div>
</template>

// src/components/pages/checkout/ship-address/saved-block/address-item/index.tsx
import { AddressType } from "@/lib/type";

export function AddressItem(address: AddressType) {
  return (
    <div className="flex flex-col grow">
      <span className="text-lg text-[#1A1A1A] mb-2">
        {address.fname} {address.lname}
      </span>
      <span className="text-base text-gray-label">{address.address}</span>
      <span className="text-base text-gray-label">
        {address.city},{address.state}, {address.zipCode}
      </span>
      <span className="text-base text-gray-label">{address.phone}</span>
    </div>
  );
}
