// components/common/CartItem/index.tsx
import { useDispatch } from "react-redux";
import { ReactNode } from "react";
import { updateCount } from "../../../store/cartSlice";
import Counter from "../Counter";

const CartItem = ({ cartItem }: { cartItem: any }) => {
  const dispatch = useDispatch();
  return (
    <div className="flex items-center gap-3">
      <div className="w-[100px] h-[133px]">
        <img
          src={cartItem?.src}
          alt=""
          className="w-full h-full object-cover"
        />
      </div>
      <div className="flex flex-col flex-grow">
        <span className="text-sm text-black mb-1 uppercase">
          {cartItem.title}
        </span>
        <p className="text-[12px] text-grayLabel line-clamp-1">
          {cartItem.description}
        </p>

        <div className="my-3">
          <Counter
            count={cartItem.count}
            minusClick={() =>
              dispatch(
                updateCount({
                  method: "minus",
                  _id: cartItem._id,
                })
              )
            }
            plusClick={() =>
              dispatch(
                updateCount({
                  method: "plus",
                  _id: cartItem._id,
                })
              )
            }
          />
        </div>
        <span className="text-primary text-sm">${cartItem.price}</span>
      </div>
    </div>
  );
};

export default CartItem;

export const CartItemButton = ({
  children,
  onClick,
}: {
  children: ReactNode;
  onClick: () => void;
}) => {
  return (
    <button
      className="w-5 h-5 border border-grayLight rounded-full"
      onClick={onClick}
    >
      {children}
    </button>
  );
};

// nuxt-version/components/common/cart-item.vue
<script setup lang="ts">
import Counter from "@/components/common/counter/counter-index.vue";
import type { CartItemType } from "@/shared/type";
import { cn } from "@/shared/utils";
import { useCartStore } from "@/shared/stores";

const {
  withCount = true,
  class: className,
  item: cartItem,
} = defineProps<{ item: CartItemType; withCount?: boolean; class?: string }>();

const { updateCount } = useCartStore();

const handleCount = (num: number) => {
  updateCount({
    num,
    _id: cartItem._id,
  });
};
</script>

<template>
  <div
    :class="cn('flex items-center gap-3', className)"
    v-show="!!cartItem"
  >
    <img
      :src="cartItem?.src || ''"
      :alt="cartItem?.title"
      class="object-cover w-25"
      width="100"
      height="133"
    />
    <div class="flex flex-col flex-grow">
      <span class="text-sm text-black mb-1 uppercase">
        {{ cartItem?.title }}
      </span>
      <p class="text-[12px] text-gray-label line-clamp-1">
        {{ cartItem?.description }}
      </p>
      <Counter
        class="my-3"
        :count="cartItem?.count || 0"
        :onClick="handleCount"
        v-show="withCount"
      />
      <span :class="cn('text-primary text-sm', withCount ? '' : 'mt-[10px]')">
        ${{ cartItem?.price || 0 }}
      </span>
    </div>
  </div>
</template>
