// components/pages/checkout/TopTitle/index.tsx
import Divider from "../../../common/Divider";
import HeadLine2 from "../../../common/HeadLine2";

const TopTitle = ({ title }: { title: string }) => {
  return (
    <div className="w-fit flex flex-col items-center justify-center m-auto gap-2 mb-5">
      <HeadLine2>{title}</HeadLine2>
      <Divider />
    </div>
  );
};

export default TopTitle;

// nuxt-version/components/common/top-title.vue
<script setup lang="ts">
import Divider from './divider-comp.vue'
import HeadLine2 from './headline2-comp.vue'

const { title } = defineProps<{ title: string }>()
</script>

<template>
  <div class="w-fit flex flex-col items-center justify-center mx-auto gap-2 mb-5">
    <HeadLine2>{{ title }}</HeadLine2>
    <Divider />
  </div>
</template>
