// vue-version/src/components/pages/checkout/saved-block/card-item.vue
<script setup lang="ts">
import MasterIcon from '@/components/icons/master-icon.vue'
import VisaIcon from '@/components/icons/visa-icon.vue'
import type { CardType } from '@/lib/type'
import { isMasterCard } from '@/lib/utils'
import { computed } from 'vue'

const { card } = defineProps<{
  card: CardType
}>()

const cardType = computed(() => isMasterCard(card.cardNumber))
</script>

<template>
  <div class="flex items-center gap-2">
    <MasterIcon v-if="!cardType" />
    <VisaIcon class="[&>path]:fill-black" v-else />
    {{ cardType ? 'Mastercard' : 'Visa' }}
    ending &bull;&bull;&bull;&bull; {{ card?.cardNumber.slice(-2) }}
  </div>
</template>

// src/components/pages/checkout/ship-address/saved-block/card-item/index.tsx
import { MasterCard, Visa } from "@/components/icons";
import { CardType } from "@/lib/type";
import { isMasterCard } from "@/lib/utils";
import { useMemo } from "react";

export default function CardItem(card: CardType) {
  const cardType = useMemo(() => isMasterCard(card.cardNumber), [card]);
  return (
    <div className="flex items-center gap-2">
      {cardType ? <MasterCard /> : <Visa className="[&>path]:fill-black" />}
      {cardType ? "Mastercard" : "Visa"} ending &bull;&bull;&bull;&bull;
      {card?.cardNumber.slice(-2)}
    </div>
  );
}
