// src/components/common/Counter/counter-button.tsx
import Button from "@/components/ui/button";
import classNames from "classnames";

export default function CounterButton(
  props: {
    disabled?: boolean;
    onClick: () => void;
  } & React.PropsWithChildren
) {
  return (
    <Button
      className={classNames(
        "!size-5 border border-gray-light rounded-full bg-transparent !p-0",
        props.disabled ? "pointer-events-none opacity-50" : ""
      )}
      onClick={props.onClick}
    >
      {props.children}
    </Button>
  );
}

// vue-version/src/components/common/counter/counter-button.vue
<script setup lang="ts">
import Button from '@/components/ui/button-ui.vue'
import { cn } from '@/lib/utils'

const props = defineProps<{ disabled?: boolean; onClick: () => void }>()
</script>
<template>
  <Button
    :class="
      cn(
        '!size-5 border border-[#C4C4C4] rounded-full bg-transparent !p-0',
        props.disabled ? 'pointer-events-none opacity-50' : '',
      )
    "
    :onClick="props.onClick"
  >
    <slot>Button content</slot>
  </Button>
</template>
