// nuxt-version/pages/index.vue
<script setup lang="ts">
import Banner from "@/components/pages/main/banner-comp.vue";
import Arrival from "@/components/pages/main/arrival-comp.vue";
import Logos from "@/components/pages/main/logos-comp.vue";
import Just4U from "@/components/pages/main/just-4u.vue";
import Collections from "@/components/pages/main/collections-comp.vue";
import Trends from "@/components/pages/main/trends-comp.vue";
import OpenFashion from "@/components/pages/main/open-fashion.vue";
</script>
<template>
  <Banner />
  <Arrival />
  <Logos />
  <Just4U />
  <Collections />
  <Trends />
  <OpenFashion />
</template>

// pages/index.tsx
import type { NextPage } from "next";
import Layout from "../components/common/Layout";
import Banner from "../components/pages/main/Banner";
import Arrival from "../components/pages/main/Arrival";
import Logos from "../components/pages/main/Logos";
import Collections from "../components/pages/main/Collections";
import Just4U from "../components/pages/main/Just4U";
import Trend from "../components/pages/main/Trend";
import OpenFashion from "../components/pages/main/OpenFashion";
const Home: NextPage = () => {

  return (
    <Layout>
      <Banner />
      <Arrival />
      <Logos />
      <Collections />
      <Just4U />
      <Trend />
      <OpenFashion />
    </Layout>
  );
};

export default Home;
