// nuxt-version/components/pages/main/just-4u.vue
<script setup lang="ts">
import ProductCard from "@/components/common/product-card.vue";
import Slider from "@/components/common/slider-comp.vue";
import TopTitle from "@/components/common/top-title.vue";
import { useProductStore } from "@/shared/stores";
import { storeToRefs } from "pinia";
import { computed } from "vue";

const { goodsList } = storeToRefs(useProductStore());

const list = computed(() => goodsList?.value.slice(0, 10));
</script>

<template>
  <section class="py-16 px-4">
    <TopTitle title="Just for you" />
    <div class="max-w-[1280px] mx-auto">
      <Slider
        :spaceBetween="10"
        slidesPerView="auto"
        sliderStyle="height: 100%"
        class="grey"
      >
        <swiper-slide
          v-for="product in list"
          :key="product._id"
          class="max-w-[255px]"
        >
          <ProductCard
            :product="product"
            vertical
          />
        </swiper-slide>
      </Slider>
    </div>
  </section>
</template>

// src/components/pages/main/Just4U/index.tsx
"use client";
import GoodItem from "@/components/common/good-item";
import Slider from "@/components/common/slider";
import TopTitle from "@/components/pages/checkout/TopTitle";
import { useAppSelector } from "@/lib/hooks";
import { useMemo } from "react";

export default function Just4U() {
  const { goodsList: goods } = useAppSelector((state) => state.products);

  const list = useMemo(() => goods.slice(0, 10), [goods]);

  return (
    <section className="py-16 px-4">
      <TopTitle title="Just for you" />
      <div className="max-w-[1280px] mx-auto">
        <Slider
          spaceBetween={10}
          slidesPerView="auto"
          sliderStyle={{
            height: "100%",
          }}
          className="grey"
          slideClass="max-w-[255px]"
          slides={list.map((c) => (
            <GoodItem
              {...c}
              vertical
              key={c._id}
            />
          ))}
        />
      </div>
    </section>
  );
}
