// next-version/src/components/pages/checkout/ship-address/saved-block/index.tsx
import { Forward, Plus } from "@/components/icons";
import { AddressItem } from "@/components/pages/checkout/ship-address/saved-block/address-item";
import CardItem from "@/components/pages/checkout/ship-address/saved-block/card-item";
import { AddressType, CardType } from "@/lib/type";

type SavedBlockPropType = {
  address?: AddressType | null;
  card?: CardType | null;
  type: "card" | "address";
  onClick: () => void;
};

export default function SavedBlock({
  address,
  card,
  type,
  onClick,
}: SavedBlockPropType) {
  const TITLE = type === "address" ? "Shipping address" : "Payment Method";
  const EMPTY_TITLE =
    type === "address" ? "Add shipping address" : "Add payment method";
  return (
    <>
      <span className="uppercase text-base text-gray-placeholder mb-3 flex">
        {TITLE}
      </span>
      {address || card ? (
        <div
          className="flex items-center justify-between"
          onClick={onClick}
        >
          {address && <AddressItem {...address} />}
          {card && <CardItem {...card} />}
          <Forward className="-rotate-90" />
        </div>
      ) : (
        <div
          className="flex items-center justify-between py-[13px] px-5 bg-[#F9F9F9] rounded-[44px] cursor-pointer"
          onClick={onClick}
        >
          {EMPTY_TITLE}
          <Plus />
        </div>
      )}
    </>
  );
}

// vue-version/src/components/pages/checkout/saved-block/saved-block.vue
<script setup lang="ts">
import Forward from '@/components/icons/forward-icon.vue'
import PlusIcon from '@/components/icons/plus-icon.vue'
import type { AddressType, CardType } from '@/lib/type'
import AddressItem from './address-item.vue'
import CardItem from './card-item.vue'

type SavedBlockPropType = {
  address?: AddressType | null
  card?: CardType | null
  type: 'card' | 'address'
  onClick: () => void
}

const { address, card, type, onClick } = defineProps<SavedBlockPropType>()

const TITLE = type === 'address' ? 'Shipping address' : 'Payment Method'
const EMPTY_TITLE = type === 'address' ? 'Add shipping address' : 'Add payment method'
</script>

<template>
  <span class="uppercase text-base text-[#888888] mb-3 flex">
    {{ TITLE }}
  </span>
  <div class="flex items-center justify-between" @click="onClick" v-if="address || card">
    <AddressItem :address="address" v-if="!!address" />
    <CardItem :card="card" v-if="!!card" />
    <Forward class="-rotate-90" />
  </div>
  <div
    class="flex items-center justify-between py-[13px] px-5 bg-[#F9F9F9] rounded-[44px] cursor-pointer"
    @click="onClick"
    v-show="!address && !card"
  >
    {{ EMPTY_TITLE }}
    <PlusIcon />
  </div>
</template>
