// nuxt-version/components/common/dialogs/menu-dialog/menu-item.vue
<script setup lang="ts">
import Forward from "@/components/icons/forward-icon.vue";
import type { MenuTab } from "@/shared/type";
import { cn } from "@/shared/utils";
import { onMounted, ref, useTemplateRef, watch } from "vue";

const { item: c } = defineProps<{ item: MenuTab }>();

const mainRef = useTemplateRef<HTMLDivElement>("mainRef");
const open = ref(false);
onMounted(() => {
  if (mainRef.value) {
    mainRef.value.style.height = "0px";
  }
});

watch(open, () => {
  if (mainRef.value) {
    mainRef.value.style.height = `${
      open.value ? mainRef.value.scrollHeight : 0
    }px`;
  }
});

const onOpen = () => (open.value = !open.value);
</script>

<template>
  <div :class="cn('overflow-hidden pt-5', open && 'pb-5')">
    <div
      class="flex gap-4 items-center justify-between pb-4 cursor-pointer"
      @click="onOpen"
    >
      <span class="flex flex-grow text-4"> {{ c.title }}</span>
      <span :class="cn('transition-all', open ? 'rotate-180' : 'rotate-0')">
        <Forward />
      </span>
    </div>
    <div
      class="flex flex-col gap-4 transition-all pl-5"
      ref="mainRef"
    >
      <NuxtLink
        :to="ci.link"
        :key="ci.title"
        v-for="ci in c.list"
      >
        {{ ci.title }}</NuxtLink
      >
    </div>
  </div>
</template>

// src/components/common/dialogs/menu-dialog/menu-item/index.tsx
import { Forward } from "@/components/icons";
import { MenuTab } from "@/lib/type";
import classNames from "classnames";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";

export default function MenuItem(c: MenuTab) {
  const ref = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (ref.current) {
      ref.current.style.height = `${open ? ref.current.scrollHeight : 0}px`;
    }
  }, [open]);
  return (
    <div className={classNames("overflow-hidden pt-5", open && "pb-5")}>
      <div
        className="flex gap-4 items-center justify-between pb-4 cursor-pointer"
        onClick={() => setOpen(!open)}
      >
        <span className="flex flex-grow text-4"> {c.title}</span>
        <span
          className={classNames(
            "transition-all",
            open ? "rotate-180" : "rotate-0"
          )}
        >
          <Forward />
        </span>
      </div>
      <div
        className="flex flex-col gap-4 transition-all pl-5"
        ref={ref}
      >
        {c.list?.map((ci) => (
          <Link
            href={ci.link}
            key={ci.title}
          >
            {ci.title}
          </Link>
        ))}
      </div>
    </div>
  );
}
